<?php

define('SENDGRID_AUTH_METHOD', 'apikey');
define('SENDGRID_API_KEY', $_ENV['SENDGRID_API_KEY']);
define('SENDGRID_FROM_NAME', $_ENV['SENDGRID_FROM_NAME']);
define('SENDGRID_FROM_EMAIL', $_ENV['SENDGRID_FROM_EMAIL']);
